################################################################################
# Build a go-environment-image to speed up the application image generation
################################################################################
FROM golang:1.15.12-alpine3.13 AS builder

RUN apk update && apk add --no-cache gcc build-base make
