version: '3.7'

networks:
  dev_net:
    name: dev_net    
    external: false

services:

  tests:
    build:
      dockerfile: ./docker/test/Dockerfile
      context: ./..
    container_name: roommgr-tests
    networks:
      - dev_net
  