// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package automodel

var TableNames = struct {
	Companies    string
	Reservations string
	Rooms        string
	Users        string
}{
	Companies:    "companies",
	Reservations: "reservations",
	Rooms:        "rooms",
	Users:        "users",
}
